--140pg
SELECT ENAME
  FROM EMP
 WHERE DEPTNO = '20';
 
SELECT ENAME, JOB, SAL, DEPTNO
  FROM EMP e 
 WHERE DEPTNO = 20
   AND JOB = 'analyst';

--142pg
SELECT *
  FROM EMP e 
 WHERE SAL != 5000;
 
SELECT *
  FROM EMP e 
 WHERE SAL = (SELECT MAX(SAL)
 			    FROM EMP);
 			    
 --144pg 와일드카드
SELECT *
  FROM EMP e 
 WHERE ENAME LIKE 'M%';
 
--145pg null
SELECT *
  FROM EMP e 
 WHERE COMM IS NULL;
--오류
SELECT *
  FROM EMP e 
 WHERE COMM = NULL;
 

--147pg
SELECT EMPNO, ENAME, SAL, DEPTNO, JOB
  FROM EMP e 
 WHERE JOB = 'CLERK'
UNION
SELECT EMPNO, ENAME, SAL, DEPTNO, JOB
  FROM EMP e 
 WHERE JOB = 'SALESMAN';

--컬럼이 일치하지 않을 경우
SELECT EMPNO, ENAME, SAL, DEPTNO, JOB
  FROM EMP e 
 WHERE DEPTNO = 10
UNION
SELECT EMPNO, ENAME, SAL, JOB
  FROM EMP e 
 WHERE DEPTNO = 20;

--148pg
SELECT EMPNO, ENAME, SAL, DEPTNO, JOB
  FROM EMP e 
 WHERE DEPTNO = 10
UNION ALL
SELECT EMPNO, ENAME, SAL, DEPTNO, JOB
  FROM EMP e 
 WHERE DEPTNO = 20;

SELECT EMPNO, ENAME, SAL, DEPTNO
  FROM EMP e 
 MINUS
SELECT EMPNO, ENAME, SAL, DEPTNO
  FROM EMP e 
 WHERE DEPTNO = 10;
 
--오라클함수 151pg
SELECT *
  FROM v$sqlfn_metadata;
  
 --152pg
 
SELECT *
  FROM EMP e 
 WHERE UPPER(ENAME) = UPPER('scott');
 
SELECT *
  FROM EMP e 
 WHERE LENGTH(ENAME) >= 5;
 
--153pg
SELECT *
  FROM EMP e 
 WHERE INSTR(ENAME,'S') > 0;

--154pg
SELECT '010-1234-5678' AS REPLACE_BEFORE
		,REPLACE('010-1234-5678', '-', '') AS REPLACE_1
		,REPLACE('010-1234-5678', '-') AS REPLACE_2
  FROM DUAL;
 
SELECT 'Oracle'
		, LPAD('Oracle', 10, '#') AS LPAD_1
		, RPAD('Oracle', 10, '*') AS RPAD_1
		, LPAD('Oracle', 10) AS LPAD_2
		, RPAD('Oracle', 10) AS RPAD_2
  FROM DUAL;
		
 SELECT RPAD('971225-', 14, '*') AS RPAD_JMNO
 		, RPAD('010-6801-', 13, '*') AS RPAD_PHONE
  FROM DUAL;
 		
 --155pg
SELECT EMPNO
		, ENAME
		, CONCAT(EMPNO, ENAME)
		, CONCAT(EMPNO, CONCAT(':', ENAME))
  FROM EMP e 
 WHERE ENAME = 'SMITH';
 
--158pg 날짜함수
SELECT SYSDATE AS NOW
		, SYSDATE-1 AS YESTERDAY
		, SYSDATE+1 AS TOMORROW
  FROM DUAL;

SELECT SYSDATE
		, ADD_MONTHS(SYSDATE, 3)
  FROM DUAL;
  
SELECT EMPNO
		, ENAME
		, HIREDATE
		, ADD_MONTHS(HIREDATE, 12*20) AS WORK10YEAR
  FROM EMP;
  
 SELECT EMPNO
 		, ENAME
 		, HIREDATE
 		, SYSDATE
   FROM EMP e
  WHERE ADD_MONTHS(HIREDATE, 12*40) > SYSDATE;
 
 --159pg
SELECT SYSDATE
		,NEXT_DAY(SYSDATE, '월요일')
		,LAST_DAY(SYSDATE)
  FROM DUAL;
  
 