SELECT EMPNO AS "EMPLOYEE_NO", ENAME AS "EMPLOYEE_NAME", JOB, MGR AS "MANAGER", SAL AS "SALARY", comm AS "COMMISSION", DEPTNO AS "DEPARTMENT_NO"
FROM emp
ORDER BY deptno DESC, ename ASC;


SELECT *
FROM emp;

SELECT *
FROM EMP;
WHERE COMM IS NULL
  AND SAL IS NOT NULL;